# Generated by Django 5.2.1 on 2025-05-21 21:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('species', models.CharField(choices=[('Dog', 'Köpek'), ('Cat', 'Kedi'), ('Bird', 'Kuş'), ('Other', 'Diğer')], max_length=20, verbose_name='Tür')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Irk')),
                ('age', models.PositiveIntegerField(verbose_name='Yaş')),
                ('gender', models.CharField(choices=[('Male', 'Erkek'), ('Female', 'Dişi')], max_length=10, verbose_name='Cinsiyet')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('last_seen_location', models.CharField(max_length=255, verbose_name='Son Görülme Yeri')),
                ('last_seen_date', models.DateField(default=datetime.date(2025, 1, 1), verbose_name='Son Görülme Tarihi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Resim')),
                ('status', models.CharField(choices=[('Lost', 'Kayıp'), ('Found', 'Bulundu'), ('Returned', 'Teslim Edildi')], default='Lost', max_length=20, verbose_name='Durum')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='Bildirim Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='mainpage.tag', verbose_name='Etiketler')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date_seen', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_method', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sightings/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='mainpage.pet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
