# Generated by Django 5.2.1 on 2025-05-17 13:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_pet_adoptionrequest_delete_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.RenameField(
        model_name='pet',
        old_name='date_posted',
        new_name='date_reported',
    ),
    migrations.AddField(
    model_name='pet',
    name='last_seen_date',
    field=models.DateField(default=datetime.date(2024, 1, 1)),
    preserve_default=False,
    ),
    migrations.AddField(
        model_name='pet',
        name='last_seen_location',
        field=models.CharField(default='Unknown', max_length=255),
        preserve_default=False,
    ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Returned', 'Returned')], default='Lost', max_length=20),
        ),
        migrations.CreateModel(
            name='SightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date_seen', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
