# Generated by Django 5.2.1 on 2025-05-17 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_rename_date_posted_pet_date_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkek'), ('Female', 'Dişi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_seen_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Dog', 'Köpek'), ('Cat', 'Kedi'), ('Bird', 'Kuş'), ('Other', 'Diğer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Lost', 'Kayıp'), ('Found', 'Bulundu'), ('Returned', 'Teslim Edildi')], default='Lost', max_length=20),
        ),
    ]
