# Generated by Django 5.2.1 on 2025-05-17 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_pet_gender_alter_pet_last_seen_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Irk'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bildirim Tarihi'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkek'), ('Female', 'Dişi')], max_length=10, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_seen_date',
            field=models.DateField(default=datetime.date(2025, 1, 1), verbose_name='Son Görülme Tarihi'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_seen_location',
            field=models.CharField(max_length=255, verbose_name='Son Görülme Yeri'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Dog', 'Köpek'), ('Cat', 'Kedi'), ('Bird', 'Kuş'), ('Other', 'Diğer')], max_length=20, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Lost', 'Kayıp'), ('Found', 'Bulundu'), ('Returned', 'Teslim Edildi')], default='Lost', max_length=20, verbose_name='Durum'),
        ),
    ]
