# Generated by Django 5.2.1 on 2025-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_pet_age_alter_pet_breed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainpage.tag', verbose_name='Etiketler'),
        ),
    ]
