# Generated by Django 5.2.1 on 2025-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_petsighting_delete_sightreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsighting',
            name='contact_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='petsighting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sightings/'),
        ),
    ]
